FROM registry.access.redhat.com/ubi9/python-312@sha256:a12a2ef4e1ecd34c0d149397ee281b703c0b58d345279c8a8015d46680207399

LABEL maintainer="blagovest@petrovs.info"
LABEL name="electrohold-bill-importer"


COPY electrohold.py requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt


CMD ["python3", "electrohold.py"]